# config/tasks.yaml
research_task:
  description: >
    Perform a web search for the latest news about Payoneer from reputable sources.
    Identify at least three high-quality articles published in the last 24 hours.
  expected_output: >
    A list of three article titles with links and brief summaries.
  agent: researcher

analysis_task:
  description: >
    Take the articles found by the researcher and create a structured report.
    Summarize each article in 3-4 sentences, including the title and URL.
  expected_output: >
    A formatted news report with three summarized articles, including source links.
  agent: analyst
  output_file: payoneer_news_report.md
